### ISSUE TITLE
Give VOC equipment to Haulage

### ISSUE THREAD

**Issue by MaZderMind** [linuxaudio/conference2018#34]
Pickup would be on 11.06. **after 14:00**, just like with delivery (#24):

> Ab Berlin - 11.06. 14:00 Uhr or later
> David R**** - +49 176 *** *** 63
> c-base e.V.
> Rungestrasse 20
> 10179 Berlin tc

**Comment by MaZderMind** [comment]
@dvzrv @ri0t can you confirm that? I would like to plan the next shipping with our Haulage this week.

**Comment by dvzrv** [comment]
@MaZderMind yes, this should work!

**Comment by dvzrv** [comment]
@MaZderMind hope you can get another spedition. Those guys were terrible...
Today they showed up at c-base at 13:00, without even calling...

**Comment by MaZderMind** [comment]
Do you mean I should try to schedule another pickup?

Or rather try a different one in the future?

**Comment by dvzrv** [comment]
@MaZderMind The 2nd thing. It was picked up some time after 14:00 eventually (the person present at c-base at 13:00 sent the driver away) afaik.

It's just weird, that they neither keep their schedule, nor call up front. Nothing you can change (, but to change to a different service, I suppose).

Thanks for taking care of the transportation otherwise! :)
